apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: swift-rgw
  namespace: openstack
spec:
  metadataPool:
    failureDomain: osd
    replicated:
      size: 1
  dataPool:
    failureDomain: osd
    erasureCoded:
      dataChunks: 2
      codingChunks: 1
  auth:
    keystone:
      acceptedRoles:
        - admin
        - member
        - service
      implicitTenants: "swift"
      revocationInterval: 1200
      serviceUserSecretName: swift-openrc
      tokenCacheSize: 1000
      url: http://keystone-api.openstack.svc.cluster.local:5000
  protocols:
    swift:
      accountInUrl: true
      urlPrefix: swift
    # note that s3 is enabled by default if protocols.s3.enabled is not explicitly set to false
  preservePoolsOnDelete: true
  gateway:
    sslCertificateRef:
    port: 80
    # securePort: 443
    instances: 1
---
apiVersion: v1
kind: Service
metadata:
  name: rook-ceph-rgw-swift-rgw-external
  namespace: openstack
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 32536
      name: http
  selector:
    app: rook-ceph-rgw
    ceph_daemon_id: swift-rgw
    rgw: swift-rgw
    rook_cluster: openstack
    rook_object_store: swift-rgw