# This is a basic workflow to help you get started with Actions

name: OpenStack Helm workflows

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    paths-ignore:
      - '.github/**'
    branches: [ "master" ]
    types: [opened, reopened]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    if: contains(github.event.pull_request.labels.*.name, 'nova')
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Check Helm
      - name: Check Helm
        shell: bash
        run: |
          which helm || (echo "Install helm on runner first" && exit 1)

      # Add helm repo
      - name: openstack helm repo
        shell: bash
        run: |
          helm repo add openstack-helm https://tarballs.opendev.org/openstack/openstack-helm

      # Run helm upgrade
      - name: Update new config
        run: |
          helm upgrade --install nova openstack-helm/nova \
              --namespace=openstack \
              --set bootstrap.wait_for_computes.enabled=true \
              --set conf.ceph.enabled=true \
              --values nova/2023.2-ubuntu_jammy.yaml \
              --values nova/values_overrides/nova_conf.yml \
              --values domain.yml